services:
  - type: web
    name: cynthiastayscurated
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22
